### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [ACBSmith/anton-chekhov_three-sisters_julius-west#1]
Colophon:
- [x] `se typogrify .` needs to make some changes in the colophon.

Stage Directions:
- [x] Your "editorial stage directions" are footnotes. These need to be converted to endnotes. We only use the editorial class if we are adding stage directions that are from different editions.

Act 1:
- [x] The inline stage direction, `<i epub:type="z3998:stage-direction">Gets up and sings softly.</i>`, should be placed right after the `<blockquote>` and surrounded with a `<p>`.

Content.opf:
- [x] Standards have changed regarding "role" properties. For each person, there must only be one "role" and other attributes use "se:role" The multiple role properties create epubcheck errors when building. See [section 9.10.5](https://standardebooks.org/manual/1.5.0/9-metadata#9.10.5) in the manual for more information.

- [x] The Wikipedia link for the production should to be https://en.m.wikipedia.org/wiki/Three_Sisters_(play)

- [x] The artist's name should to be filed as "Borch, Gerard ter".

**Comment by ACBSmith** [comment]
All issues addressed, and re-built manifest/spine/toc for endnotes. Lint is clean again.

**Comment by EmmaSweeney** [comment]
epubcheck is still throwing an error.

**Comment by ACBSmith** [comment]
Whoops, missed an se:role. It's building cleanly now.
